version: '3'

services:
  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier
    environment:
      - POSTGRES_PASSWORD=password

  db:
    image: postgres
    restart: always
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password

  result:
    build: ./result
    restart: always
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
    - POSTGRES_PASSWORD=password

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: